// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhXB15TsLuDUTGKX_oOrW4HtswNMNcmIk',
    appId: '1:317734015226:web:88961e07d691aa49baf943',
    messagingSenderId: '317734015226',
    projectId: 'abukaf-herbs-aa01e',
    authDomain: 'abukaf-herbs-aa01e.firebaseapp.com',
    storageBucket: 'abukaf-herbs-aa01e.firebasestorage.app',
    measurementId: 'G-RNV99YX57R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIqtmSjQ0KvzA5xdj_gfAgBH8ZFGf_5Js',
    appId: '1:769782009060:android:16dc949bdc345a18fb30f1',
    messagingSenderId: '769782009060',
    projectId: 'abukaf-herbs',
    storageBucket: 'abukaf-herbs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-dxT0IE1O8w7FdPHx1upqNiDn7iS6TLI',
    appId: '1:769782009060:ios:1477b0239efd584afb30f1',
    messagingSenderId: '769782009060',
    projectId: 'abukaf-herbs',
    storageBucket: 'abukaf-herbs.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-dxT0IE1O8w7FdPHx1upqNiDn7iS6TLI',
    appId: '1:769782009060:ios:1477b0239efd584afb30f1',
    messagingSenderId: '769782009060',
    projectId: 'abukaf-herbs',
    storageBucket: 'abukaf-herbs.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXR4AFw9F9vT399fLV9Iy1ElggTt63I9g',
    appId: '1:769782009060:web:78eff0fa4066d397fb30f1',
    messagingSenderId: '769782009060',
    projectId: 'abukaf-herbs',
    authDomain: 'abukaf-herbs.firebaseapp.com',
    storageBucket: 'abukaf-herbs.firebasestorage.app',
    measurementId: 'G-N3T6F46772',
  );
}